<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_test</name>
   <tag></tag>
   <elementGuidId>032b1b6a-a6e0-41d8-a1b9-36fbed443581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#test</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='test']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4bbc9708-2a43-42bc-8264-e9a53e9b0def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>f70d3fbb-b695-4679-8be0-5c877812900d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye unitinfo add-tooltip</value>
      <webElementGuid>3b37d03c-a58b-4496-9d80-006db74e67da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>04063004-7c3f-4d2f-be96-ceada6f92624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>c2b4c943-3040-414c-b4ce-ec7209963e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>(enter with country code e.g. 278328XXXX)</value>
      <webElementGuid>7c7ce0a9-3b9e-4af0-a199-1bfeb92fbfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test&quot;)</value>
      <webElementGuid>2163793f-a62a-4130-80dc-8c997042c8b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='test']</value>
      <webElementGuid>726fd40f-83d1-45a2-9123-5a121827dba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='viewPassword']/i</value>
      <webElementGuid>5b85ff5e-2d34-4178-8be3-3806cacd8545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>1b019cb1-16d5-424a-8a00-7ce66f840ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'test']</value>
      <webElementGuid>3c0c1664-72b4-4ce4-ab4b-d446b2a295e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
