<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Next_fa fa-spinner fa-spin</name>
   <tag></tag>
   <elementGuidId>fa42e70e-f9c7-45e1-a2a8-e0ae922424d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-spinner.fa-spin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-save-fake']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4dced0d3-f8c7-406a-aeca-aac7e8d6d53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-spinner fa-spin</value>
      <webElementGuid>53fda010-aec7-4490-8907-6209e99d6fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39f84674-24b4-461f-a1e0-ab3f1a523bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-save-fake&quot;)/i[@class=&quot;fa fa-spinner fa-spin&quot;]</value>
      <webElementGuid>7b0c0162-920a-4d84-9e25-2a484f5bccdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-save-fake']/i</value>
      <webElementGuid>4441c696-5009-4a7c-8ba8-f5e935e5c6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/i</value>
      <webElementGuid>ccada159-942c-498a-84d0-d64e98b5e924</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
