<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Name_ctl00cphBodytxtFleetName</name>
   <tag></tag>
   <elementGuidId>89e211f3-4e1a-4ec0-a5e8-3b09577dc781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_txtFleetName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cphBody_txtFleetName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a5d48be-b386-4040-bb9b-5d42e8fa2d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$txtFleetName</value>
      <webElementGuid>e8eb9bd7-4775-439b-b70f-4d1f320aab64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b08e4666-eb24-4765-a82b-1976bbb80b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Amanda trucks</value>
      <webElementGuid>34d8e23c-dcfa-4ba9-969c-b88c39e456eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_txtFleetName</value>
      <webElementGuid>efa1d540-2baf-489a-9dc9-42fc6a5bc280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textboxMandatory form-control</value>
      <webElementGuid>10e0fafb-e66c-47da-bfda-292cca689861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_txtFleetName&quot;)</value>
      <webElementGuid>b26e3438-b14a-4c5a-844d-173bad953cfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cphBody_txtFleetName']</value>
      <webElementGuid>16070002-d43b-432c-99f1-540812ace0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[2]/div/div/input</value>
      <webElementGuid>a670f645-f528-49cf-a591-11e7bf8128cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>fa27421f-6bf6-4a6d-a0f8-ae1ae9aa3468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphBody$txtFleetName' and @type = 'text' and @id = 'cphBody_txtFleetName']</value>
      <webElementGuid>97cc7181-b888-4e33-a0ca-66016a43bb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cphBody_CustomerDetail']/div[2]/div/div/input</value>
      <webElementGuid>ca23fb13-5dfb-4f98-95d7-33a4875401db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>7a7f48fb-8734-4dde-8967-dfe7008bc325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
