<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Account Number_ctl00cphBodyt_7cdb18</name>
   <tag></tag>
   <elementGuidId>858bfc21-7e08-44bf-bb87-f1f187e178b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_txtCustomerMobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cphBody_txtCustomerMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>836b9c3e-42a5-4701-a837-c974909b7156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$txtCustomerMobileNumber</value>
      <webElementGuid>19cfd7c4-1530-41a5-b62d-bf7a837ad4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98cce95f-d497-4cc5-9815-999a3b300345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>IMPL70459</value>
      <webElementGuid>618a1cc4-8281-4d12-8fe3-ce3c5aa56d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_txtCustomerMobileNumber</value>
      <webElementGuid>caa6b163-0ae9-4624-a23d-709c79c3c4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>a99754a3-8b52-47de-b458-086660c9dbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled textboxMandatory form-control</value>
      <webElementGuid>03463206-4545-4f8b-a702-ebc6da86d64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_txtCustomerMobileNumber&quot;)</value>
      <webElementGuid>c6f24118-82f1-49db-a0c7-4ce1a20d6b07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cphBody_txtCustomerMobileNumber']</value>
      <webElementGuid>d1e0f2b4-ec36-40ce-93e3-988f7ab1edc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div/div/div/input</value>
      <webElementGuid>a73b3a6a-81c6-4a78-aca6-985399ca7c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>74160efd-f2a4-40d0-b35d-d0818bf83d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphBody$txtCustomerMobileNumber' and @type = 'text' and @id = 'cphBody_txtCustomerMobileNumber']</value>
      <webElementGuid>ea599d34-676f-47f2-8137-f871386b4f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cphBody_CustomerDetail']/div/div/div/input</value>
      <webElementGuid>3c2b5aed-cad8-490f-943d-b9c13780bb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>cbbc3943-45ef-4569-a319-945af3a551ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
