<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cash Customer_ctl00cphBodychkCashCustomer</name>
   <tag></tag>
   <elementGuidId>9c9e9208-62c5-4a48-8122-baa36d51d664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_chkCashCustomer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cphBody_chkCashCustomer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84405bc6-442d-4fc8-a94b-0d2b36604e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_chkCashCustomer</value>
      <webElementGuid>4a71280e-eda0-4a73-884d-6fa915d096d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e637345a-dd1f-44a7-a431-815a1fe40927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$chkCashCustomer</value>
      <webElementGuid>b10dc496-490d-48dd-8b9f-a051cd0be559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_chkCashCustomer&quot;)</value>
      <webElementGuid>3907cb3b-5f74-4d4c-8434-2c78e565508f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cphBody_chkCashCustomer']</value>
      <webElementGuid>188674ad-8fdb-43d5-a69b-0ac817138198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[6]/div/div/input</value>
      <webElementGuid>64390dfd-ce94-41bb-afd4-4ff9298958d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>83b6f038-929b-4dc2-80de-c7f8824a71d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cphBody_chkCashCustomer' and @type = 'checkbox' and @name = 'ctl00$cphBody$chkCashCustomer']</value>
      <webElementGuid>9e8f91bb-708a-4ba5-9296-34aafd8acabd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
