<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_ctl00cphBodytxtCustomerEmail</name>
   <tag></tag>
   <elementGuidId>0629e40f-9bd8-479c-9687-737429db6b7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_txtCustomerEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cphBody_txtCustomerEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85036699-f95e-4b6c-b4c4-7b7d0091255a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$txtCustomerEmail</value>
      <webElementGuid>67549f20-edee-47d0-b762-4f8906a13ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>183b1657-f359-4f08-b19e-a5040e118763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_txtCustomerEmail</value>
      <webElementGuid>a2d116a7-9baf-47de-baf2-2643813887aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textboxMandatory form-control</value>
      <webElementGuid>e6834b4c-c7e1-48ec-9f98-0ff1074d0235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_txtCustomerEmail&quot;)</value>
      <webElementGuid>0bb77a65-e462-4570-b3a8-2f2ab0c003e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cphBody_txtCustomerEmail']</value>
      <webElementGuid>7304581c-5115-4bdb-9cc1-53e04276bd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[3]/div/div/input</value>
      <webElementGuid>0dc851bf-8796-4c60-a249-4cd9d314cc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>fda7faa6-377f-4f53-8608-c737627cd5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphBody$txtCustomerEmail' and @type = 'text' and @id = 'cphBody_txtCustomerEmail']</value>
      <webElementGuid>863b80ef-1016-4213-86a6-2010cf211805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
