<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Capture Driver_ctl00cphBodychkAddDriver</name>
   <tag></tag>
   <elementGuidId>9a657951-e2a4-4843-a112-28ac148ee937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_chkAddDriver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cphBody_chkAddDriver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6bd88df-c182-42c4-9d82-e3ecbf46e561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_chkAddDriver</value>
      <webElementGuid>b6e7250f-4e29-4405-9f2c-ff445fc40a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>be98d24b-1311-4c01-9158-6b9566d62bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$chkAddDriver</value>
      <webElementGuid>b6ce128d-37bf-4636-b208-6d246e4b1241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>440f0187-aba0-4a92-8a41-0b0b1c238929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$cphBody$chkAddDriver\',\'\')', 0)</value>
      <webElementGuid>6db8913c-009a-4d72-b014-70c14b326ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_chkAddDriver&quot;)</value>
      <webElementGuid>545ad70a-3b26-4fc9-bb70-a04730cb7eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cphBody_chkAddDriver']</value>
      <webElementGuid>f11ed1ab-32d8-498d-9ca6-a5808490147e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[8]/div/div/input</value>
      <webElementGuid>d070da57-1066-4bf7-94d9-ac045195b931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>94f57a1a-6383-423a-95aa-edc39f0c8596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cphBody_chkAddDriver' and @type = 'checkbox' and @name = 'ctl00$cphBody$chkAddDriver' and @checked = 'checked']</value>
      <webElementGuid>6e41f132-4bba-4316-8bf6-4704a22ca681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
