<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Export_ctl00cphBodybtnAddIndividual</name>
   <tag></tag>
   <elementGuidId>41562faf-6099-458c-af3c-38cd6e6a82cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_btnAddIndividual</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cphBody_btnAddIndividual']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>427979b8-7e1b-4fbc-95fd-ad983153f57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c2ebf987-e33a-400d-a380-95455711501c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$btnAddIndividual</value>
      <webElementGuid>eb31fd32-5faf-4d88-988f-c4ae4cbce68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>New Individual Application</value>
      <webElementGuid>a0679cda-7d43-4dd4-9853-f62e24d4f066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_btnAddIndividual</value>
      <webElementGuid>7cdaa594-ffe2-4823-81fe-1cb087048cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success tip-s medium grey</value>
      <webElementGuid>c875285c-e553-4cf4-994c-1e92e11e0067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_btnAddIndividual&quot;)</value>
      <webElementGuid>d850e878-b0e3-4aea-b7b2-8afad18b853e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cphBody_btnAddIndividual']</value>
      <webElementGuid>e038cda8-ee3e-4bf2-b82f-9e763c1911e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cphBody_buttonsDiv']/div/input</value>
      <webElementGuid>5118ee0d-2f3d-4a1e-9588-fd732fb128e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>608c3b38-f086-4d15-9fdc-f748d74cc866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$cphBody$btnAddIndividual' and @id = 'cphBody_btnAddIndividual']</value>
      <webElementGuid>8cf56e61-5487-4a06-925c-bc04883182d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
