<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Generators  Other_ctl00cphBodychkAddG_fa3c03</name>
   <tag></tag>
   <elementGuidId>001e8e30-9967-4525-9922-845683fd167b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_chkAddGenerator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cphBody_chkAddGenerator']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12667bfe-8134-4c6a-aa3f-f091a2da13a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_chkAddGenerator</value>
      <webElementGuid>497d8f94-6d8b-4ac3-a8e9-9771b6ffd87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>24b429a2-a15c-4d49-a903-2c3f394b8740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$chkAddGenerator</value>
      <webElementGuid>12b96e5b-b0f5-49ca-a3e3-d418609fcd98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$cphBody$chkAddGenerator\',\'\')', 0)</value>
      <webElementGuid>41dfb700-f2de-4ce3-bacc-20adfd991485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_chkAddGenerator&quot;)</value>
      <webElementGuid>73b2f0e6-4ee1-4162-94e3-aea737f8e793</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cphBody_chkAddGenerator']</value>
      <webElementGuid>48979715-f41e-4b41-8f84-5e9f8b347a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[9]/div/div/input</value>
      <webElementGuid>e5658716-bb1f-489e-8508-400c6a5ebcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>e6a8bccd-6d19-4ab0-b76e-180d7c873fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cphBody_chkAddGenerator' and @type = 'checkbox' and @name = 'ctl00$cphBody$chkAddGenerator']</value>
      <webElementGuid>7d4fca46-e54e-475d-954c-e5d5f46b3fcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
