<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Capture Vehicle_ctl00cphBodychkAddVehicle</name>
   <tag></tag>
   <elementGuidId>595559a8-8e59-431a-93ec-423f8994cb2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_chkAddVehicle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cphBody_chkAddVehicle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74eab06f-546d-463a-a417-1c7ec626bc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_chkAddVehicle</value>
      <webElementGuid>95f0e59c-f0a6-43a1-94de-38c23b2f404b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f84a6348-3108-4803-bdbd-6ee2eee031ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$chkAddVehicle</value>
      <webElementGuid>4bb54893-1690-42c9-ab76-54a1e9c47b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>ccc52fdb-926c-42c0-a116-f9280b6d7c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$cphBody$chkAddVehicle\',\'\')', 0)</value>
      <webElementGuid>c54c12c0-3dfe-48e5-a62d-2e82433b2764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_chkAddVehicle&quot;)</value>
      <webElementGuid>f8036464-0405-4a67-acf4-9a7ebdc8b7d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cphBody_chkAddVehicle']</value>
      <webElementGuid>6fb95f9e-b6dd-486a-8f66-76e0ac3d88d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[7]/div/div/input</value>
      <webElementGuid>dc973177-44fc-48be-afa6-1b363c6303ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>6f4151f4-3338-4967-b222-e422e03c3a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cphBody_chkAddVehicle' and @type = 'checkbox' and @name = 'ctl00$cphBody$chkAddVehicle' and @checked = 'checked']</value>
      <webElementGuid>e220cdb5-73f0-4466-8f45-6745e2bd7bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
