<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_SAR Customer Group 1</name>
   <tag></tag>
   <elementGuidId>cfd1e36b-2d92-4d28-83ac-2cdafe9e7d5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-cphBody_selCustomerGroup-result-29jk-6561</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-cphBody_selCustomerGroup-result-29jk-6561']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>144ec6ec-8f2a-4b62-bce0-8583c1922865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>5ebc22a9-90a8-4bba-9296-02141b0fcc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-cphBody_selCustomerGroup-result-29jk-6561</value>
      <webElementGuid>68b8c929-9c86-47b2-8065-a721666e236b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>07b9bb52-a9a8-4abc-af88-53f92cc14a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3306bd2a-e7f9-469f-b320-e91eef0820df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAR Customer Group 1</value>
      <webElementGuid>5231be4e-8097-45c4-9f7f-a02f2d4d51cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-cphBody_selCustomerGroup-result-29jk-6561&quot;)</value>
      <webElementGuid>333ca0ca-f0ef-48ee-9f7c-e55f32bedfc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-cphBody_selCustomerGroup-result-29jk-6561']</value>
      <webElementGuid>44111546-7502-4b3d-b2bc-ac6513ef5e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-cphBody_selCustomerGroup-results']/li[17]</value>
      <webElementGuid>73abee85-bfd2-4b1a-bd61-d4325cf5d235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LLP'])[2]/following::li[1]</value>
      <webElementGuid>ec6893f9-ee89-43cf-837b-64e89be21c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanker Services - Fuel and Gas'])[2]/following::li[2]</value>
      <webElementGuid>099ba072-2cf3-4c3d-82c7-1c48d5660bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAR Customer Group 2'])[2]/preceding::li[1]</value>
      <webElementGuid>3e936c81-cc29-4144-ae13-8ccf2a884f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synchrony Customer Group'])[3]/preceding::li[2]</value>
      <webElementGuid>7c0521a1-f0a4-4cc4-8bd0-726afcc396b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[17]</value>
      <webElementGuid>ddf8c8a9-062b-4ad4-b98f-1b2e017a321c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-cphBody_selCustomerGroup-result-29jk-6561' and (text() = 'SAR Customer Group 1' or . = 'SAR Customer Group 1')]</value>
      <webElementGuid>91c6f5a6-ea2d-4cb4-b811-a67d85034fa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
