<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PendingActiveClosedFraudSuspended</name>
   <tag></tag>
   <elementGuidId>3dd246f0-b3b1-4f1e-8a30-1762356e2c63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_selCustomerStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cphBody_selCustomerStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ff5eb6e-3d56-4235-a9e0-4bad98131414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$selCustomerStatus</value>
      <webElementGuid>3162ad07-c34b-43db-bf84-76268e0a4d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_selCustomerStatus</value>
      <webElementGuid>a112dbe8-913a-4b6c-8838-064b9ad704ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectbox select-chr form-control</value>
      <webElementGuid>1558891e-d9f1-41f6-9a8a-f942af9eb576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Pending
		Active
		Closed
		Fraud
		Suspended

	</value>
      <webElementGuid>0a8665c1-b9f6-4125-a7f6-79564ab75963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_selCustomerStatus&quot;)</value>
      <webElementGuid>cb8f2a72-56eb-423c-8467-30cee1332204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cphBody_selCustomerStatus']</value>
      <webElementGuid>18b1e623-b4b2-41e5-aab1-e5b7a96db1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cphBody_CustomerDetail']/div[4]/div/div/select</value>
      <webElementGuid>bbd8ce08-d186-4b15-80ed-07c22393739a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Status'])[1]/following::select[1]</value>
      <webElementGuid>f2f7058c-f290-4acf-8ce5-a57e55f8c6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fast n Fresh'])[1]/following::select[1]</value>
      <webElementGuid>691df575-ec9e-4d99-a462-50f94f7e89b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::select[1]</value>
      <webElementGuid>496e655c-da38-4de0-895e-86a1eebb2036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Type'])[1]/preceding::select[1]</value>
      <webElementGuid>5921e434-dc3d-4214-9a15-bf3149b544f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>ac908517-3fcd-454c-a3f3-bde4b5dd8242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$cphBody$selCustomerStatus' and @id = 'cphBody_selCustomerStatus' and (text() = '
		Pending
		Active
		Closed
		Fraud
		Suspended

	' or . = '
		Pending
		Active
		Closed
		Fraud
		Suspended

	')]</value>
      <webElementGuid>5d39d1b2-8e1b-4ee4-85d3-c111d94ab3bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
