<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SAR Customer Group 1</name>
   <tag></tag>
   <elementGuidId>9be93625-0ba1-4438-b72b-9e474a77342d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-cphBody_selCustomerGroup-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-cphBody_selCustomerGroup-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42f3371f-31a4-47d1-9e95-0378b91e07a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a9a85d8e-a1e5-4976-a1fc-f269f54f2298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-cphBody_selCustomerGroup-container</value>
      <webElementGuid>dcc5f323-a9b3-4137-b468-5dbdaececefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SAR Customer Group 1</value>
      <webElementGuid>1436bf26-44d0-421d-bb33-c56176b547c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAR Customer Group 1</value>
      <webElementGuid>95c06b3c-9cef-4487-b96e-d95bab61a0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-cphBody_selCustomerGroup-container&quot;)</value>
      <webElementGuid>ae3bd355-e3e2-4c86-b003-3eb50b1f2c95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-cphBody_selCustomerGroup-container']</value>
      <webElementGuid>f275b7b6-bd2a-460a-a8f6-70a2bdd6d525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[4]/div/div/span/span/span/span</value>
      <webElementGuid>3491b737-06cd-4e6d-9fe4-3a000d3ace12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Group'])[1]/following::span[4]</value>
      <webElementGuid>cedd9060-1274-419c-b15a-c9b5e3fb2496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[4]</value>
      <webElementGuid>705b9762-dced-4ea8-8304-2d4039402f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::span[3]</value>
      <webElementGuid>f2354e08-5e9c-462d-9146-3c938e0fd6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Customer'])[1]/preceding::span[3]</value>
      <webElementGuid>8ebd64f8-fabe-4aee-a390-6c2f581feba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>8348496c-c6d3-4ff3-a6c4-9d4456f344fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-cphBody_selCustomerGroup-container' and @title = 'SAR Customer Group 1' and (text() = 'SAR Customer Group 1' or . = 'SAR Customer Group 1')]</value>
      <webElementGuid>2e49c6b4-0723-4d99-a582-f2183183e2a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
