<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Not Applicable</name>
   <tag></tag>
   <elementGuidId>2de44a01-cd25-4762-92ed-21dc09052950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-cphBody_selCustomerGroup-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-cphBody_selCustomerGroup-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58309118-2f59-4446-ad3d-3a483ef68362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>8cb15094-927b-4c61-8d59-9903be153851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-cphBody_selCustomerGroup-container</value>
      <webElementGuid>e25da562-73d4-4dc2-8363-de234f2451cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Not Applicable</value>
      <webElementGuid>4250cc78-a2bb-4c01-a253-ec243f2ebbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Applicable</value>
      <webElementGuid>0804f09d-f1d0-477f-8339-1cf35dc4efb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-cphBody_selCustomerGroup-container&quot;)</value>
      <webElementGuid>d838ebb3-ac52-43f3-94db-a27eda58057b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-cphBody_selCustomerGroup-container']</value>
      <webElementGuid>7a04c2fb-4dcf-4bf2-add3-c46bb1ca7d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[4]/div/div/span/span/span/span</value>
      <webElementGuid>4b62b0aa-003f-4630-835c-8c6b9c04bae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Group'])[1]/following::span[4]</value>
      <webElementGuid>39e64eb4-9335-4b84-b415-af16059ed12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[4]</value>
      <webElementGuid>1900df29-50c5-4803-954e-2239fc39594b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::span[3]</value>
      <webElementGuid>1ee2b85b-ebee-462b-b63e-bf38e5a7fc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Customer'])[1]/preceding::span[3]</value>
      <webElementGuid>39c7fdd2-3752-45ae-b906-cd753957e3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>307e6399-e1c2-4514-8e79-7f4900c7b6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-cphBody_selCustomerGroup-container' and @title = 'Not Applicable' and (text() = 'Not Applicable' or . = 'Not Applicable')]</value>
      <webElementGuid>315e0c27-b0e4-4779-9e0c-d18c14884bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
