<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Customer Address_ctl00cphBodytxtCu_317f95</name>
   <tag></tag>
   <elementGuidId>9a35b052-30e1-4f93-9551-4eeaa564f7a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphBody_txtCustmerAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='cphBody_txtCustmerAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5fbdefa6-e2ed-4cdd-bf1c-ab17fe85fb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphBody$txtCustmerAddress</value>
      <webElementGuid>281cdf38-6dc1-4ed0-bc12-2ea73a96d58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>40042f2a-a861-4cba-85c8-5a3871073964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9a6b9b57-1927-4d88-a408-b9c161229ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cphBody_txtCustmerAddress</value>
      <webElementGuid>3057d3a7-6987-4201-9e52-ecbb4f7bda67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textboxMandatory form-control</value>
      <webElementGuid>8a149af2-a8a1-4a97-aa8a-ac7e4fd1da0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cphBody_txtCustmerAddress&quot;)</value>
      <webElementGuid>9cb45aa8-9919-4d89-8291-873abcd7815c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='cphBody_txtCustmerAddress']</value>
      <webElementGuid>21940165-24bb-4f65-a3a0-77d820f25f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo_step_tab1']/div[10]/div/div/textarea</value>
      <webElementGuid>b9e1ff8e-ae51-4abe-9cbb-e2768342eaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>33aa336d-4e9a-41bb-bd5e-1bcca6261cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$cphBody$txtCustmerAddress' and @id = 'cphBody_txtCustmerAddress']</value>
      <webElementGuid>efcbdfa7-df86-4d96-b443-1b141a131509</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
